import { useEffect } from "react";
import { Helmet } from "react-helmet-async";
import Navbar from "../components/Navbar";
import { useLoading } from "../context/LoadingProvider";
import "../wtrweb.css";

const htmlContent = `<div class="policy-page-wrapper">
        
        <div class="policy-header">
            <div class="container" style="display: flex; gap: 24px;">
                <a href="/terms" style="color: var(--brand); font-weight: 600;">General Terms</a>
                <a href="#" style="color: var(--text-secondary);">Supplier Agreements</a>
                <a href="#" style="color: var(--text-secondary);">Subscription Policies</a>
            </div>
        </div>

        
        <div class="policy-layout">

            
            <aside class="policy-sidebar policy-sidebar-left">
                <div class="policy-nav-group">
                    <div class="policy-nav-title">Legal & Policies</div>
                    <ul class="policy-nav-list">
                        <li><a href="/guidelines" class="policy-nav-link">Guidelines and Policies</a></li>
                        <li><a href="/privacy" class="policy-nav-link">Privacy Policy</a></li>
                        <li><a href="/terms" class="policy-nav-link active">Terms of Service</a></li>
                        <li><a href="#" class="policy-nav-link">Cookie Policy</a></li>
                        <li><a href="#" class="policy-nav-link">Licenses & Registration</a></li>
                    </ul>
                </div>
                <div class="policy-nav-group">
                    <div class="policy-nav-title">Platform</div>
                    <ul class="policy-nav-list">
                        <li><a href="#" class="policy-nav-link">Delivery Areas</a></li>
                        <li><a href="#" class="policy-nav-link">Subscription Terms</a></li>
                        <li><a href="#" class="policy-nav-link">Supplier Verification</a></li>
                    </ul>
                </div>
            </aside>

            
            <main class="policy-content-area">
                <div class="policy-breadcrumbs">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"></path>
                        <path d="M9 22V12h6v10"></path>
                    </svg>
                    <span>></span>
                    <span>Terms and Conditions</span>
                </div>

                <h1 class="policy-title">Terms and Conditions – WtrDrop</h1>

                <div class="policy-body">

                    <h2 id="general">1. GENERAL, PREAMBLE, AND INTERPRETATION</h2>
                    <p>1.1. <strong>Company Information:</strong> WtrDrop, having its office at J-3 J-Extn, Kishan Kunj, Laxmi Nagar, New Delhi, Delhi – 110092, India (hereinafter referred to as "WtrDrop", "Company", "we", "us", or "our") exclusively owns, manages, hosts, and operates the digital technology platform accessible via the website WtrDrop.in and associated mobile applications available on iOS, Android, and other operating systems (collectively referred to as the "App" or "Platform").</p>
                    <p>1.2. <strong>E-Commerce Entity Classification:</strong> Under the Consumer Protection (E-Commerce) Rules, 2020, WtrDrop strictly operates as a marketplace e-commerce entity. We provide an information technology platform on a digital network to facilitate transactions between buyers and sellers. WtrDrop does not own, stock, or hold any inventory of the Products listed on the App.</p>
                    <p>1.3. <strong>Intermediary Status & Statutory Compliance:</strong> While WtrDrop acts as a technology intermediary facilitating the connection between Customers, independent water suppliers ("Suppliers"), and independent third-party logistics providers ("Delivery Partners"), we acknowledge our obligations under the Consumer Protection Act, 2019, and the Information Technology Act, 2000. Nothing in these Terms excludes, restricts, or modifies any liability that cannot be legally excluded under applicable Indian law.</p>
                    <p>1.4. <strong>Electronic Record:</strong> This document is an electronic record in terms of the Information Technology Act, 2000, and rules generated thereunder as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                    <p>1.5. <strong>Binding Agreement:</strong> By accessing, browsing, downloading, installing, registering on, or otherwise using the App, you irrevocably agree to comply with and be bound by these Terms and Conditions ("Terms"). If you do not agree, you must immediately cease all use of the App.</p>

                    <h2 id="user-eligibility">2. USER ELIGIBILITY AND REPRESENTATIONS</h2>
                    <p>2.1. <strong>Age Requirement:</strong> Access to and use of the App is strictly limited to individuals who are at least eighteen (18) years of age, or the age of legal majority in your respective jurisdiction, and who can form legally binding contracts under the Indian Contract Act, 1872.</p>
                    <p>2.2. <strong>Representations and Warranties:</strong> By utilizing the App, you unequivocally represent that you possess the absolute legal capacity to enter into these Terms, and that all registration and profile information you submit is strictly truthful, accurate, current, and complete.</p>

                    <h2 id="data-privacy">3. DATA PRIVACY AND DPDP ACT COMPLIANCE</h2>
                    <p>3.1. <strong>Statutory Alignment:</strong> WtrDrop is fully committed to protecting your personal data in strict compliance with the Digital Personal Data Protection Act, 2023 (DPDP Act), and other applicable data protection laws in India.</p>
                    <p>3.2. <strong>Consent Mechanism and Processing Basis:</strong> By registering on the App, you provide explicit, free, specific, informed, and unambiguous consent for WtrDrop to collect, process, and store your personal data strictly for the purpose of facilitating orders, improving platform functionality, and ensuring legal compliance. You retain rights to access, correct, or request erasure of your data under applicable law.</p>

                    <h2 id="platform-operations">4. PLATFORM OPERATIONS, ORDER FLOW, AND SLA CLARITY</h2>
                    <p>4.1. <strong>System Processing:</strong> Orders placed on the App are processed through automated algorithms matching Customers with Suppliers and Delivery Partners.</p>
                    <p>4.2. <strong>Service Level Agreement (SLA):</strong> WtrDrop strives to ensure timely deliveries. If an order is delayed beyond 120 minutes from the original confirmed ETA without valid operational reasoning (e.g., severe weather), the Customer is eligible to raise an SLA breach ticket for potential compensation via App wallet credits or partial delivery fee refunds.</p>

                    <h2 id="pricing-structure">5. PRICING STRUCTURE AND LIMITATION OF CONTROL</h2>
                    <p>5.1. <strong>Components of Pricing:</strong> The total amount payable includes Product Cost, Delivery Charges, Platform Fees, Handling Fees, Surge/Dynamic Pricing, and applicable GST.</p>
                    <p>5.2. <strong>Pricing Origination and Algorithms:</strong> WtrDrop provides algorithmic pricing tools for network optimization, dynamic matching, and balancing supply with demand. However, the base pricing originates from Supplier inputs, which are then subject to platform algorithms. The final total price displayed to the Customer at the exact moment of order confirmation is binding for that specific transaction.</p>

                    <h2 id="commission">6. COMMISSION, REVENUE MODEL, AND SETTLEMENTS</h2>
                    <p>6.1. WtrDrop generates revenue through commissions, platform fees, and delivery charge margins, maintaining authority to automatically deduct applicable fees and taxes at the source before executing settlements.</p>
                    <p>6.2. <strong>Ledger Finality (Subject to Audit):</strong> The digital ledgers generated by WtrDrop’s backend systems are considered binding. However, this is strictly subject to audit, reconciliation, and applicable law. Financial disputes may be raised within 7 days of statement generation.</p>

                    <h2 id="payment">7. SECURE PAYMENT TERMS AND GATEWAYS</h2>
                    <p>7.1. All online payments are processed via RBI-approved, secure, third-party payment gateways. WtrDrop operates as an intermediary and does not directly process these transactions or store sensitive PCI-DSS data.</p>

                    <h2 id="supplier-obligations">8. SUPPLIER OBLIGATIONS, COMPLIANCE, AND TRANSPARENCY</h2>
                    <p>8.1. <strong>Mandatory KYC & Verification:</strong> All Suppliers must undergo a mandatory KYC process. Failure to provide accurate KYC documents, FSSAI licenses, or GST details will result in immediate suspension.</p>
                    <p>8.2. <strong>Country of Origin Disclosure:</strong> In compliance with applicable e-commerce rules, Suppliers are legally mandated to provide the "Country of Origin" and manufacturing details for all packaged Products. WtrDrop relies on Supplier declarations and will display this information on the listing page where applicable.</p>
                    <p>8.3. <strong>Ranking and Listing Transparency:</strong> WtrDrop ranks and displays Suppliers to Customers based on a composite algorithm that primarily considers proximity (distance), estimated time of arrival (ETA), and historical Customer ratings. Suppliers may optionally participate in "Promoted/Sponsored Listings" (clearly marked as "Ad" or "Promoted" on the App) in exchange for a fee, which will temporarily boost their visibility independent of the organic ranking algorithm.</p>

                    <h2 id="delivery-partner">9. DELIVERY PARTNER TERMS AND RISK TRANSFER</h2>
                    <p>9.1. <strong>Independent Contractor Status:</strong> Delivery Partners are independent contractors responsible for providing their own compliant vehicles, fuel, and mobile devices.</p>
                    <p>9.2. <strong>Insurance and Risk Transfer:</strong> Delivery Partners are exclusively responsible for procuring and maintaining adequate personal accident, vehicle, and third-party liability insurance. Given the physical nature of water delivery, WtrDrop strictly disclaims liability for any personal injury or property damage (e.g., floor scratches, broken fixtures) caused by the Delivery Partner at the Customer's premises. The risk and liability lie solely with the independent Delivery Partner fulfilling the order.</p>

                    <h2 id="customer-obligations">10. STRICT CUSTOMER OBLIGATIONS AND PLATFORM MISUSE</h2>
                    <p>10.1. <strong>Fulfillment of Details:</strong> Customers must provide accurate delivery addresses and ensure availability to receive the delivery.</p>
                    <p>10.2. <strong>Prohibited Conduct & Anti-Automation:</strong> Customers explicitly agree NOT to:</p>
                    <ul>
                        <li>Engage in verbal/physical abuse against any platform user.</li>
                        <li>Provide structurally compromised empty cans during exchanges.</li>
                        <li>Misuse the Platform via Automation: The use of bots, scrapers, automated scripts, unauthorized API access, or automated bulk-ordering algorithms to manipulate supply, bypass surge pricing, or harvest platform data is strictly prohibited and will result in immediate IP bans and legal action.</li>
                    </ul>

                    <h2 id="cancellation-refunds">11. EXHAUSTIVE CANCELLATION, REFUNDS, AND RETURN POLICY</h2>
                    <p>11.1. <strong>Structured Refund Scenarios:</strong> WtrDrop guarantees refunds under the following scenarios:</p>
                    <ul>
                        <li>Non-Delivery by Supplier or Delivery Partner.</li>
                        <li>Missing Items from the confirmed order.</li>
                        <li>Defective/Damaged Goods (requires photographic evidence within 12 hours).</li>
                    </ul>
                    <p>11.2. <strong>Strict No-Return Policy for Non-Damaged Goods:</strong> Given that the Products (water cans) are consumable goods subject to strict hygiene standards, WtrDrop enforces a strict "No Return" policy for changes of mind or incorrect ordering by the Customer once the seal is broken or the product is delivered. Returns are ONLY authorized if the product is proven to be structurally defective, contaminated, or damaged upon arrival.</p>
                    <p>11.3. <strong>Processing:</strong> Approved refunds will be initiated within 24 to 48 business hours, reflecting in 5 to 7 business days depending on banking infrastructure.</p>

                    <h2 id="anti-fraud">12. ANTI-FRAUD, SYSTEM ABUSE, AND ASSET RECOVERY</h2>
                    <p>12.1. In the event WtrDrop detects fraudulent activity (e.g., fake trip generation, promo abuse), WtrDrop possesses the absolute right to block accounts, reverse fraudulent payouts, deduct owed amounts from future settlements, freeze wallet balances, and initiate formal legal recovery proceedings to recover defrauded funds.</p>

                    <h2 id="limitation-liability">13. COMPREHENSIVE LIMITATION OF LIABILITY AND INDEMNIFICATION</h2>
                    <p>13.1. <strong>General Disclaimer:</strong> THE APP AND SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS.</p>
                    <p>13.2. <strong>Health Liability Shielding:</strong> Water is a consumable product. While WtrDrop mandates FSSAI compliance for Suppliers, we cannot physically inspect inventory. Customers are strictly advised to independently verify Supplier FSSAI certifications, hygiene ratings, and product seals displayed on or delivered via the App before consumption. WtrDrop shall not be liable for health complications arising exclusively from the Supplier's negligence.</p>
                    <p>13.3. <strong>Statutory Override:</strong> Nothing in these Terms excludes liability where such exclusion is not permitted under the Consumer Protection Act, 2019, or Information Technology Act, 2000.</p>

                    <h2 id="intellectual-property">14. INTELLECTUAL PROPERTY & THIRD-PARTY SERVICES</h2>
                    <p>14.1. All intellectual property associated with the App remains the sole property of WtrDrop. The App relies on third-party services (payment processors, mapping APIs), and WtrDrop bears no direct liability for outages originating strictly from these external entities.</p>

                    <h2 id="suspension-termination">15. SUSPENSION, TERMINATION, AND FORCE MAJEURE</h2>
                    <p>15.1. WtrDrop reserves the right to suspend or terminate access for a suspected breach of these Terms. Neither party shall be liable for delays caused by Force Majeure events beyond reasonable control (natural disasters, pandemics, internet outages).</p>

                    <h2 id="miscellaneous">16. MISCELLANEOUS AND SEVERABILITY</h2>
                    <p>16.1. <strong>Severability:</strong> If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions, and the remaining provisions of these Terms shall remain in full force and effect.</p>

                    <h2 id="governing-law">17. GOVERNING LAW, JURISDICTION, AND DISPUTE RESOLUTION</h2>
                    <p>17.1. <strong>Governing Law:</strong> These Terms shall be strictly governed by the laws of India.</p>
                    <p>17.2. <strong>Fair Arbitration Clause:</strong> Any dispute arising out of these Terms shall be determined by binding arbitration in New Delhi. To ensure fairness, the arbitration shall be conducted by a mutually appointed single arbitrator. If the parties cannot agree within 30 days, the appointment shall be referred to a recognized neutral arbitration body in India. The language of arbitration shall be English.</p>

                    <h2 id="contact-info">18. CONTACT INFORMATION AND ESCALATION MATRIX</h2>
                    <p>18.1. <strong>Grievance Redressal & Escalation Matrix:</strong> In compliance with the Information Technology Rules, 2021, and the Consumer Protection (E-Commerce) Rules, 2020:</p>
                    <ul>
                        <li>Level 1 (Customer Support Desk): Contact via App Help Center. Response Time: 24 hours. Resolution Time: 3-5 days.</li>
                        <li>Level 2 (Grievance Officer): Email: Query@wtrdrop.in. Response: 48 hours. Resolution: Max 15 days.</li>
                    </ul>
                </div>
            </main>

            
            <aside class="policy-sidebar policy-sidebar-right">
                <div class="policy-toc">
                    <a href="#general" class="policy-toc-link">1. General & Interpretation</a>
                    <a href="#user-eligibility" class="policy-toc-link">2. User Eligibility</a>
                    <a href="#data-privacy" class="policy-toc-link">3. Data Privacy Compliance</a>
                    <a href="#platform-operations" class="policy-toc-link">4. Platform Operations & SLA</a>
                    <a href="#pricing-structure" class="policy-toc-link">5. Pricing Structure</a>
                    <a href="#commission" class="policy-toc-link">6. Commission & Revenue</a>
                    <a href="#payment" class="policy-toc-link">7. Secure Payment Terms</a>
                    <a href="#supplier-obligations" class="policy-toc-link">8. Supplier Obligations</a>
                    <a href="#delivery-partner" class="policy-toc-link">9. Delivery Partner Terms</a>
                    <a href="#customer-obligations" class="policy-toc-link">10. Customer Obligations</a>
                    <a href="#cancellation-refunds" class="policy-toc-link">11. Cancellation & Refunds</a>
                    <a href="#anti-fraud" class="policy-toc-link">12. Anti-Fraud & Abuse</a>
                    <a href="#limitation-liability" class="policy-toc-link">13. Limitation of Liability</a>
                    <a href="#intellectual-property" class="policy-toc-link">14. Intellectual Property</a>
                    <a href="#suspension-termination" class="policy-toc-link">15. Suspension & Force Majeure</a>
                    <a href="#miscellaneous" class="policy-toc-link">16. Miscellaneous</a>
                    <a href="#governing-law" class="policy-toc-link">17. Governing Law</a>
                    <a href="#contact-info" class="policy-toc-link">18. Contact Information</a>
                </div>
            </aside>

        </div>
    </div>

    `;

export default function Terms() {
  const { setLoading } = useLoading();

  useEffect(() => {
    setLoading(100);
  }, [setLoading]);

 return (
  <>
    <Helmet>
      <title>Terms & Conditions - WtrDrop</title>

      <meta
        name="description"
        content="Read the official Terms & Conditions for using the WtrDrop platform, website and mobile applications."
      />

      <meta
        name="keywords"
        content="WtrDrop, Terms and Conditions, Terms of Service, Water Delivery App"
      />

      <link
        rel="canonical"
        href="https://wtrdrop.in/terms"
      />

      {/* Open Graph */}
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="WtrDrop" />
      <meta property="og:title" content="Terms & Conditions - WtrDrop" />
      <meta
        property="og:description"
        content="Read the official Terms & Conditions for using the WtrDrop platform."
      />
      <meta
        property="og:url"
        content="https://wtrdrop.in/terms"
      />
      <meta
        property="og:image"
        content="https://wtrdrop.in/clogo.png"
      />

      {/* Twitter */}
      <meta
        name="twitter:card"
        content="summary_large_image"
      />
      <meta
        name="twitter:title"
        content="Terms & Conditions - WtrDrop"
      />
      <meta
        name="twitter:description"
        content="Read the official Terms & Conditions for using the WtrDrop platform."
      />
      <meta
        name="twitter:image"
        content="https://wtrdrop.in/clogo.png"
      />
    </Helmet>

    <Navbar />
      <div id="smooth-wrapper">
        <div id="smooth-content">
          <div 
            className="static-page-container" 
            dangerouslySetInnerHTML={{ __html: htmlContent }} 
          />
        </div>
      </div>
    </>
  );
}
